### ISSUE TITLE
等比例实现正方形

### ISSUE THREAD

**Issue by fuhangyy** [fuhangyy/CSS-Blog#1]

**Comment by fuhangyy** [comment]
现在有很多移动端的项目和PC端的项目中都有类似实现等比例缩放的正方形，下面有三种方案可以实现等比例缩放正方形。同时也各有优缺点

方案一：采用CSS3中的vw单位

CSS3 中新增了一组相对于可视区域百分比的长度单位vw、vh、vmin、vmax。其中vw是相对于视口宽度百分比的单位，1vw = 1% viewport width，vh是相对于视口高度百分比的单位，1vh = 1% viewport height；vmin是相对当前视口宽高中较小的一个的百分比单位，同理 vmax是相对当前视口宽高中较大的一个的百分比单位。
```css
.square-container1 {
  width: 20%;
  height: 20vw;
  background: rgb(0, 255, 115);
}
```

```html
<div class="square-container1"></div>
```
优点：代码简洁方便
缺点：兼容性不好，具体可参考源文件的中例子，可以很清晰的看到

方案二：使用垂直方向的padding值将高度撑开

由于margin, padding 的百分比数值是相对父元素的宽度计算的，只需将元素垂直方向的一个padding值设定为与width相同的百分比就可以制作出自适应正方形了。

但要注意，仅仅设置padding-bottom是不够的，若向容器添加内容，内容会占据一定高度，为了解决这个问题，需要设置height: 0。
```css
.square-container2 {
  width: 20%;
  height: 0;
  padding-bottom: 20%;
  background: rgb(241, 27, 27);
}
```
```html
<div class="square-container2"></div>
```
优点：代码简洁明了，且兼容性好。
缺点：元素上面不能限制最大宽度，也就是不能设置max-width。

方案三：通用伪元素来撑开元素的高度（方案二的改进版）

由于方案二中的max-width属性限制了宽度的原因，而padding-bottom的值是和width的百分比一致的，所以最后会导致宽高的比例不一致。
解决的方案就是可以通过添加一个子元素去撑开父元素的高度。
```css
.square-container3 {
  width: 20%;
  max-width: 300px;
}

.square-container3:after {
  display: block;
  content: '';
  padding-bottom: 100%;
  background: rgb(132, 0, 255);
}
```
```html
<div class="square-container3"></div>
```
备注：也可以不使用伪元素，通过给父元素添加一个子元素也可以实现，但是使用伪元素可以减少一个空标签

结合以上三种方案可以看出方案三不仅兼容性好，而且避免了max-width的约束，所以在项目中可以大胆放心的使用第三种方案去实现等比例缩放正方形了。
